# install_fix_llm_v2.py
# اصلاح llm_analyzer.py
# اجرا: python install_fix_llm_v2.py

import os
import sys
import shutil
from pathlib import Path
from datetime import datetime

if os.name == 'nt':
    os.system('chcp 65001 >nul 2>&1')

try:
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8', errors='ignore')
except:
    pass

PROJECT_ROOT = Path(r"F:\python\har roz ba python\smart_bours")
AI_FILE = PROJECT_ROOT / "ai" / "llm_analyzer.py"


def safe_print(text):
    try:
        print(text)
    except UnicodeEncodeError:
        print(text.encode('ascii', errors='ignore').decode('ascii'))


def main():
    safe_print("")
    safe_print("=" * 70)
    safe_print("  🔧 اصلاح llm_analyzer.py")
    safe_print("=" * 70)
    safe_print("")

    if not AI_FILE.exists():
        safe_print(f"❌ {AI_FILE} پیدا نشد!")
        input("Enter...")
        return

    # ===== بکاپ =====
    safe_print("[1] بکاپ گرفتن...")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = PROJECT_ROOT / "backup" / "llm_fix"
    backup_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(AI_FILE, backup_dir / f"llm_analyzer_{timestamp}.py")
    safe_print(f"   ✅ بکاپ در: {backup_dir.name}")
    safe_print("")

    # ===== نوشتن نسخه‌ی اصلاح‌شده =====
    safe_print("[2] نوشتن نسخه‌ی اصلاح‌شده...")

    lines = []
    lines.append("# ai/llm_analyzer.py")
    lines.append("# تحلیل‌گر LLM v2.1 — Groq + DeepSeek + Fallback")
    lines.append("# اجرا: python ai/llm_analyzer.py")
    lines.append("")
    lines.append("import sys")
    lines.append("import os")
    lines.append("import json")
    lines.append("import logging")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("logging.basicConfig(")
    lines.append("    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',")
    lines.append("    level=logging.INFO")
    lines.append(")")
    lines.append("logger = logging.getLogger(__name__)")
    lines.append("")
    lines.append("PROJECT_ROOT = Path(r'F:\\\\python\\\\har roz ba python\\\\smart_bours')")
    lines.append("sys.path.insert(0, str(PROJECT_ROOT))")
    lines.append("")
    lines.append("# ===== config =====")
    lines.append("CONFIG_OK = False")
    lines.append("LLM_MODE = 'auto'")
    lines.append("LLM_TEMPERATURE = 0.3")
    lines.append("LLM_MAX_TOKENS = 500")
    lines.append("SYSTEM_PROMPT = 'تو یه تحلیل‌گر بورس ایران هستی.'")
    lines.append("")
    lines.append("try:")
    lines.append("    from config.llm_config import (")
    lines.append("        DEEPSEEK_API_KEY,")
    lines.append("        GROQ_API_KEY,")
    lines.append("        GROQ_BASE_URL,")
    lines.append("        GROQ_MODEL,")
    lines.append("        LLM_MODEL,")
    lines.append("        LLM_BASE_URL,")
    lines.append("        LLM_MODE as _cfg_mode,")
    lines.append("        LLM_TEMPERATURE as _cfg_temp,")
    lines.append("        LLM_MAX_TOKENS as _cfg_max,")
    lines.append("        SYSTEM_PROMPT as _cfg_sys,")
    lines.append("    )")
    lines.append("    LLM_MODE = _cfg_mode")
    lines.append("    LLM_TEMPERATURE = _cfg_temp")
    lines.append("    LLM_MAX_TOKENS = _cfg_max")
    lines.append("    SYSTEM_PROMPT = _cfg_sys")
    lines.append("    CONFIG_OK = True")
    lines.append("except ImportError as e:")
    lines.append("    logger.warning(f'Config error: {e}')")
    lines.append("    DEEPSEEK_API_KEY = ''")
    lines.append("    GROQ_API_KEY = ''")
    lines.append("    GROQ_BASE_URL = 'https://api.groq.com/openai/v1'")
    lines.append("    GROQ_MODEL = 'llama-3.3-70b-versatile'")
    lines.append("    LLM_MODEL = 'deepseek-chat'")
    lines.append("    LLM_BASE_URL = 'https://api.deepseek.com'")
    lines.append("")
    lines.append("")
    lines.append("class LLMAnalyzer:")
    lines.append("    '''تحلیل‌گر LLM با Groq + DeepSeek + Fallback'''")
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        self.client = None")
    lines.append("        self.mode = 'fallback'")
    lines.append("        self.backend = None")
    lines.append("        self.model = None")
    lines.append("")
    lines.append("        if not CONFIG_OK:")
    lines.append("            logger.warning('Config not loaded - Fallback mode')")
    lines.append("            return")
    lines.append("")
    lines.append("        # 1. Groq")
    lines.append("        if GROQ_API_KEY and GROQ_API_KEY.startswith('gsk_'):")
    lines.append("            try:")
    lines.append("                from openai import OpenAI")
    lines.append("                self.client = OpenAI(")
    lines.append("                    api_key=GROQ_API_KEY,")
    lines.append("                    base_url=GROQ_BASE_URL")
    lines.append("                )")
    lines.append("                self.mode = 'groq'")
    lines.append("                self.backend = 'Groq'")
    lines.append("                self.model = GROQ_MODEL")
    lines.append("                logger.info(f'Groq ready ({GROQ_MODEL})')")
    lines.append("                return")
    lines.append("            except Exception as e:")
    lines.append("                logger.error(f'Groq init error: {e}')")
    lines.append("")
    lines.append("        # 2. DeepSeek")
    lines.append("        if DEEPSEEK_API_KEY and DEEPSEEK_API_KEY.startswith('sk-'):")
    lines.append("            try:")
    lines.append("                from openai import OpenAI")
    lines.append("                self.client = OpenAI(")
    lines.append("                    api_key=DEEPSEEK_API_KEY,")
    lines.append("                    base_url=LLM_BASE_URL")
    lines.append("                )")
    lines.append("                self.mode = 'deepseek'")
    lines.append("                self.backend = 'DeepSeek'")
    lines.append("                self.model = LLM_MODEL")
    lines.append("                logger.info('DeepSeek ready')")
    lines.append("                return")
    lines.append("            except Exception as e:")
    lines.append("                logger.error(f'DeepSeek init error: {e}')")
    lines.append("")
    lines.append("        # 3. Fallback")
    lines.append("        logger.warning('No LLM available - Fallback mode')")
    lines.append("        self.mode = 'fallback'")
    lines.append("")
    lines.append("    def _call_llm(self, user_prompt, system_prompt=None):")
    lines.append("        '''فراخوانی LLM'''")
    lines.append("        if not self.client:")
    lines.append("            return None")
    lines.append("        try:")
    lines.append("            response = self.client.chat.completions.create(")
    lines.append("                model=self.model,")
    lines.append("                messages=[")
    lines.append("                    {'role': 'system', 'content': system_prompt or SYSTEM_PROMPT},")
    lines.append("                    {'role': 'user', 'content': user_prompt}")
    lines.append("                ],")
    lines.append("                temperature=LLM_TEMPERATURE,")
    lines.append("                max_tokens=LLM_MAX_TOKENS")
    lines.append("            )")
    lines.append("            return response.choices[0].message.content")
    lines.append("        except Exception as e:")
    lines.append("            logger.error(f'LLM call error: {e}')")
    lines.append("            return None")
    lines.append("")
    lines.append("    def _fallback_news(self, news_text):")
    lines.append("        '''Fallback - تحلیل ساده خبر'''")
    lines.append("        try:")
    lines.append("            from news.news_sentiment import NewsSentiment")
    lines.append("            ns = NewsSentiment()")
    lines.append("            result = ns.analyze_text(news_text)")
    lines.append("            sentiment = 'neutral'")
    lines.append("            if result['score'] < 0:")
    lines.append("                sentiment = 'negative'")
    lines.append("            elif result['score'] > 0:")
    lines.append("                sentiment = 'positive'")
    lines.append("            out = {")
    lines.append("                'sentiment': sentiment,")
    lines.append("                'impact': result['score'],")
    lines.append("                'symbols': result.get('symbols', []),")
    lines.append("                'advice': 'تحلیل با Fallback (بدون LLM)',")
    lines.append("                'mode': 'fallback'")
    lines.append("            }")
    lines.append("            return json.dumps(out, ensure_ascii=False)")
    lines.append("        except Exception as e:")
    lines.append("            out = {'error': str(e), 'mode': 'fallback'}")
    lines.append("            return json.dumps(out, ensure_ascii=False)")
    lines.append("")
    lines.append("    def analyze_news(self, news_text):")
    lines.append("        '''تحلیل خبر'''")
    lines.append("        if self.mode == 'fallback':")
    lines.append("            return self._fallback_news(news_text)")
    lines.append("")
    lines.append("        prompt = 'این خبر بورسی رو تحلیل کن:\\n\\n' + news_text")
    lines.append("        prompt += '\\n\\nخروجی JSON:\\n'")
    lines.append("        prompt += '{\\n'")
    lines.append("        prompt += '  \"sentiment\": \"positive/negative/neutral\",\\n'")
    lines.append("        prompt += '  \"impact\": -10 to +10,\\n'")
    lines.append("        prompt += '  \"symbols\": [\"نمادهای تأثیرپذیر\"],\\n'")
    lines.append("        prompt += '  \"advice\": \"توصیه کوتاه فارسی\"\\n'")
    lines.append("        prompt += '}'")
    lines.append("")
    lines.append("        result = self._call_llm(prompt)")
    lines.append("        if result is None:")
    lines.append("            return self._fallback_news(news_text)")
    lines.append("        return result")
    lines.append("")
    lines.append("    def advise_stock(self, symbol, rsi, pe, change_pct):")
    lines.append("        '''مشاوره سهم'''")
    lines.append("        if self.mode == 'fallback':")
    lines.append("            return f'سهم {symbol}: RSI={rsi}, P/E={pe}, تغییر={change_pct}% (بدون LLM)'")
    lines.append("")
    lines.append("        prompt = 'این سهم رو تحلیل کن:\\n\\n'")
    lines.append("        prompt += f'نماد: {symbol}\\n'")
    lines.append("        prompt += f'RSI: {rsi}\\n'")
    lines.append("        prompt += f'P/E: {pe}\\n'")
    lines.append("        prompt += f'تغییر: {change_pct}%\\n\\n'")
    lines.append("        prompt += '۲-۳ خط توصیه به فارسی.'")
    lines.append("")
    lines.append("        result = self._call_llm(prompt)")
    lines.append("        if result is None:")
    lines.append("            return f'سهم {symbol}: RSI={rsi}, P/E={pe} (بدون LLM)'")
    lines.append("        return result")
    lines.append("")
    lines.append("")
    lines.append("# ===== تست =====")
    lines.append("if __name__ == '__main__':")
    lines.append("    analyzer = LLMAnalyzer()")
    lines.append("    print('Mode: ' + str(analyzer.mode))")
    lines.append("    print('Backend: ' + str(analyzer.backend))")
    lines.append("    print()")
    lines.append("    print('=' * 60)")
    lines.append("    result = analyzer.analyze_news('تحریم جدید خودروسازی اعمال شد')")
    lines.append("    print('Result:')")
    lines.append("    print(result)")

    content = "\n".join(lines)
    AI_FILE.write_text(content, encoding="utf-8")
    safe_print(f"   ✅ llm_analyzer.py نوشته شد ({len(content)} بایت)")
    safe_print("")

    # ===== تست =====
    safe_print("=" * 70)
    safe_print("  🧪 تست")
    safe_print("=" * 70)
    safe_print("")

    result = os.popen(f'{sys.executable} "{AI_FILE}"').read()
    safe_print(result)

    safe_print("")
    safe_print("=" * 70)
    safe_print("  🎉 تمام!")
    safe_print("=" * 70)
    safe_print("")
    safe_print("📋 قدم بعدی:")
    safe_print("   python ai\\llm_analyzer.py")
    safe_print("")

    input("  Enter...")


if __name__ == "__main__":
    main()
